Repository Mahak008/HungryBox, pull requests merged in 2025-02, with the labels that each got.

#140 fix: added city validation in cart
  README.md
  frontend/src/pages/PlaceOrder/PlaceOrder.css
  frontend/src/pages/PlaceOrder/PlaceOrder.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 5.O

#139 Migrated the whole Project to Vite for Enhanced Performance and Developer Experience
  admin/vite.config.js
  frontend/.env.example
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/App.jsx
  frontend/src/components/ExploreMenu/ExploreMenu.jsx
  frontend/src/components/FeedbackForm/Feedback.jsx
  frontend/src/components/FeedbackPopup/FeedbackPopup.jsx
  frontend/src/components/FoodDisplay/FoodDisplay.jsx
  frontend/src/components/FoodItem/FoodItem.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/HappyClients/HappyClients.jsx
  frontend/src/components/Header/Header.jsx
  frontend/src/components/KitchenToDoorstep/KitchenToDoorstep.jsx
  frontend/src/components/LoginPopup/LoginPopup.jsx
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/ThemeToggle.jsx
  frontend/src/components/TwoFactorAuth/TwoFactorAuth.jsx
  frontend/src/context/StoreContext.jsx
  frontend/src/context/ThemeContext.js
  frontend/src/context/ThemeContext.jsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/main.jsx
  frontend/src/pages/Cart/Cart.jsx
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/MyOrders/MyOrders.jsx
  frontend/src/pages/PlaceOrder/PlaceOrder.jsx
  frontend/src/pages/Subscription/Subscription.jsx
  frontend/src/pages/Verify/Verify.jsx
  frontend/src/styles/theme.css
Labels: SWOC, ADVANCE, SWOC 5.O

#147 Update HappyClients.css
  frontend/src/components/HappyClients/HappyClients.css
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#152 #145: Ensure Full-Width Boxes on Mobile
  frontend/src/components/ExploreMenu/ExploreMenu.css
  frontend/src/components/KitchenToDoorstep/KitchenToDoorstep.css
  frontend/src/index.css
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#153 UI fix of button
  frontend/src/components/FeedbackForm/Feedback.css
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O
