Repository Mahak008/HungryBox, pull requests merged in 2025-01, with the labels that each got.

#18 updated colour of 3 almost unreadable text element
  frontend/src/pages/Cart/Cart.css
Labels: good first issue, SWOC, BEGINNER, SWOC 5.O

#23 #10 styled footer
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.js
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#27 Implemented password reset feature with email service integration
  backend/controllers/userController.js
  backend/models/userModel.js
  backend/routes/userRoute.js
  frontend/src/components/LoginPopup/LoginPopup.js
Labels: SWOC, ADVANCE, SWOC 5.O

#28 Added Subscription Page
  frontend/src/App.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/Subscription/Subscription.css
  frontend/src/pages/Subscription/Subscription.js
Labels: SWOC, INTERMEDIATE, SWOC 5.O

#30 Added ContactUs page, compact footer look, fixed navbar bug & enhanced css
  frontend/src/App.js
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
  frontend/src/pages/ContactUs/ContactUs.css
  frontend/src/pages/ContactUs/ContactUs.js
Labels: bug, SWOC, INTERMEDIATE, SWOC 5.O

#54 Fix the conflicts between navbar
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
Labels: bug, SWOC, SWOC 5.O

#72 Restriction for non subscribers
  backend/controllers/cartController.js
  backend/controllers/foodController.js
  backend/models/foodModel.js
  backend/models/userModel.js
Labels: enhancement, SWOC, ADVANCE, SWOC 5.O

#98 feat: Implement Razorpay Payment Gateway by removing Stripe
  backend/.gitignore
  backend/controllers/cartController.js
  backend/controllers/orderController.js
  backend/node_modules/.package-lock.json
  backend/package-lock.json
  backend/package.json
  frontend/public/index.html
  frontend/src/pages/PlaceOrder/PlaceOrder.js
  frontend/src/pages/Verify/Verify.js
Labels: enhancement, SWOC, ADVANCE, SWOC 5.O

#96 feedback-section-fixed
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FeedbackForm/Feedback.css
  frontend/src/components/FeedbackForm/Feedback.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 5.O

#97 Fixed cart spacing issue, and light mode immunity for cart and navbar
  frontend/src/components/Navbar/Navbar.css
  frontend/src/pages/Cart/Cart.css
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#61 UI enhancement_2
  frontend/src/components/ExploreMenu/ExploreMenu.css
  frontend/src/components/ExploreMenu/ExploreMenu.js
  frontend/src/components/FoodItem/FoodItem.css
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/components/LoginPopup/LoginPopup.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/index.css
  frontend/src/pages/Cart/Cart.css
  frontend/src/pages/PlaceOrder/PlaceOrder.css
Labels: SWOC, SWOC 5.O

#101 subscriptions-page-enhanced/theme-bug-fixed
  frontend/src/App.js
  frontend/src/pages/Subscription/Subscription.css
  frontend/src/pages/Subscription/Subscription.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 5.O

#102 Added Links
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Footer/Footer.js
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#106 Fixed Footer with responsive design
  frontend/package-lock.json
  frontend/public/index.html
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.js
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#116 Complete 2 Factor Authentication including frontend and backend
  backend/models/UserOTPVerify.js
  backend/src/Services/MailSender.ts
  backend/src/controllers/Verify2FaController.js
  backend/src/controllers/userController.ts
  backend/src/routes/OTPVefication.route.js
  backend/src/server.ts
  frontend/src/assets/assets.js
  frontend/src/assets/twoFa.svg
  frontend/src/components/LoginPopup/LoginPopup.js
  frontend/src/components/TwoFactorAuth/TwoFactorAuth.css
  frontend/src/components/TwoFactorAuth/TwoFactorAuth.js
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 5.O

#110 Improvised icons for theme toggle button
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Navbar/ThemeToggle.js
Labels: good first issue, SWOC, BEGINNER, SWOC 5.O

#125 🛠️ Fix : Sign Up page name field validation added
  frontend/src/components/LoginPopup/LoginPopup.js
Labels: good first issue, SWOC, BEGINNER, SWOC 5.O

#124 Added a significant kitchen to doorstep block to the home page
  frontend/package-lock.json
  frontend/src/assets/app_screens.png
  frontend/src/assets/assets.js
  frontend/src/assets/delivery_man.png
  frontend/src/assets/home_cook.webp
  frontend/src/components/KitchenToDoorstep/KitchenToDoorstep.css
  frontend/src/components/KitchenToDoorstep/KitchenToDoorstep.js
  frontend/src/pages/Home/Home.js
Labels: enhancement, SWOC, SWOC 5.O

#117 [🐞Bug Fix]: Fixed console errors and Order component missing props error
  admin/src/App.jsx
  admin/src/components/Loading/Loading.jsx
Labels: SWOC, BEGINNER, SWOC 5.O

#120 [❗Error]: Proper dotenv config call and mongo_uri initialization
  backend/src/config/db.ts
  backend/src/server.ts
Labels: SWOC, BEGINNER, SWOC 5.O

#121 Resolved bug in hardcoded production URL and also fixes some errors in some backend files
  backend/package-lock.json
  backend/src/Services/MailSender.ts
  backend/src/controllers/Verify2FaController.ts
  backend/src/controllers/feedbackController.ts
  backend/src/models/UserOTPVerify.ts
  backend/src/routes/OTPVefication.route.ts
  frontend/.env.development
  frontend/.env.production
  frontend/src/context/StoreContext.js
Labels: bug, enhancement, SWOC, SWOC 5.O

#126 Fixed some responsiveness of the navbar
  frontend/src/App.js
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.js
  frontend/src/components/Navbar/ThemeToggle.js
Labels: SWOC, BEGINNER, SWOC 5.O

#128 Fixed Color
  frontend/src/components/ExploreMenu/ExploreMenu.css
Labels: good first issue, SWOC, BEGINNER, SWOC 5.O

#136 Added `contributors` section in `README.md`
  README.md
Labels: documentation, SWOC, BEGINNER, SWOC 5.O

#137 Added UI for scroll bar
  frontend/src/index.css
Labels: enhancement, SWOC, BEGINNER, SWOC 5.O

#138 Done adding all issue templates and pull request templates !!
  .github/ISSUE_TEMPLATE/backend_issue.yml
  .github/ISSUE_TEMPLATE/bugreport.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/frontend_issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, SWOC, BEGINNER, SWOC 5.O
